---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.haml"
  - "**.rb"

exclude_paths:
- config/**/*
- db/**/*
- test/**/*
- vendor/**/*
- app/assets/javascripts/sortable.js
- app/assets/javascripts/sortable_new.js