---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
    exclude_fingerprints:
    - 5e7d98231fe12138c448a5a76f6bcf1b
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.haml"
  - "**.rb"

exclude_paths:
- config/**/*
- db/**/*
- test/**/*
- vendor/**/*