language: ruby
rvm:
  - 2.2.4
env:
  - DB=sqlite
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test
addons:
  code_climate:
    repo_token: 1248b79f40b0f2a2616d0dbfc9ca5d164811a4761d3f7f20b9639424dd011435